### ISSUE TITLE
ALPR system not displaying the CAD character info anymore when BOLO active

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/fivem-integrations#113]
As of the latest version. I'm not sure what else to say as there are no server or client errors and the last time I tested was November 2023 when it was working fine. I've updated all integrations here to the latest versions as of today. server cfg is set up properly as it always has been as hasn't changed as per the docs.

**Comment by casperiv0** [comment]
Possible to elaborate on what isn't working. Does it show any information? Does it get stuck somewhere? Does it simply not do anything? Logs on server/client (F8 console) side?

**Comment by Legacy-TacticalGamingInteractive** [comment]
> Possible to elaborate on what isn't working. Does it show any information? Does it get stuck somewhere? Does it simply not do anything? Logs on server/client (F8 console) side?

No error logs on client or server.
Other than the sna integrations starting up as usual.

My startup order:
```
setr snailycad_url "---"
set snailycad_api_key "---"
setr snailycad_use_postal "true"
ensure sna-sync
ensure sna-alpr
ensure sna-call911
ensure sna-postals
``` 
Simply does not do anything. Our usual Wrath lock on BOLO alert shows but it does not notify with any CAD vehicle or character info like it used to do. The script is running, everything is set up as per the docs and as usual.

We lock the BOLO plate as always too.
We've double checked our methods like 30 times.

I've seen that on the Discord several others have had this issue over time but who knows what their situation was.
It used to work last time I used it with Nov 2023 version.

Wraith resource is started after the sna integration scripts in server cfg. Could that be the issue? If that was though I would expect some errors in the console. I will try anyways to put Wrath resource before sna. I will report back later today after server restart.

By the way we have:

Server Artifacts 8450.
Game build 3095.
OneSync Infiniti.
100+ players on server when tested.

**Comment by Legacy-TacticalGamingInteractive** [comment]
I have given up on this one unfortunately. No clue why its not working anymore like it did in 2023. I even tried installing old version of the integration too. Might be something FiveM changed over the past several months causing an issue.

**Comment by Legacy-TacticalGamingInteractive** [comment]
Can anyone else test on their end and let me know their artifacts version, game build, wraith script version, startup order of sna integrations? I am frustrated and at a total loss here lol considering that it used to work

**Comment by jxckUK** [comment]
Just tested this with the following:

Artifacts: 8552
Game Build: 3095
Wraith: 1.3.1
sna-alpr: 0.14.1

Load order: wk_wars2x, sna-sync, sna-alpr

Could not replicate the issue, shows me the notification with the citizen details without issue for me on this setup:

![image](https://github.com/SnailyCAD/fivem-integrations/assets/48030374/0781f7ef-b733-4750-aaac-66c73048765f)

**Comment by Legacy-TacticalGamingInteractive** [comment]
Mine all seems the same as yours.

What's your in CAD Bolo configured as? Vehicle BOLO? Person name details
and Vehicle info filled out in Cad?

Its soo weird how its not working. No errors in console either client or
server. Its almost like the event is not being called to display the nui
for whatever reason. Im going to test in my other server now as well.

**Comment by jxckUK** [comment]
> Mine all seems the same as yours. What's your in CAD Bolo configured as? Vehicle BOLO? Persons name details and Vehicle info filled out in Cad? Its soo weird how its not working. No errors in console either client or server. Its almost like the event is not being called to display the nui for whatever reason. Im going to test in my other server now as well.

Can I just clarify, when you manually lock a plate does it return the plate search if the vehicle information is filled out in the CAD?

**Comment by jxckUK** [comment]
Did some additional testing as I was concerned we were not trying the same things.

![image](https://github.com/SnailyCAD/fivem-integrations/assets/48030374/5f6dddc1-fb0c-478e-b33c-0049068a03e6)

This shows a vehicle not registered in the CAD, but with a BOLO configured. Hits fine when the plate is locked.

![image](https://github.com/SnailyCAD/fivem-integrations/assets/48030374/1bc6d9f4-6d22-4d3e-a3f2-6521d2858770)

This shows a vehicle registered in the CAD, with a BOLO configured also. Again, this hits fine when the plate is locked.

Have you modified your wraith script at all?

**Comment by Legacy-TacticalGamingInteractive** [comment]
Reinstalled WRAITH. Fixed issue. No clue why. The version was exactly the same! Gremlins in the code, man.

**Comment by jxckUK** [comment]
> Reinstalled WRAITH. Fixed issue. No clue why. The version was exactly the same! Gremlins in the code, man.

Least its fixed!
