### ISSUE TITLE
ALPR

### ISSUE THREAD

**Issue by marshular** [SnailyCAD/fivem-integrations#3]
### Describe the feature

An in-game ALPR that can pickup plates and get information such as DUIs, BOLOs, etc. Support for these scripts would be cool (https://forum.cfx.re/t/release-wraith-ars-2x-police-radar-and-plate-reader-v1-3-1/1058277 | https://forum.cfx.re/t/prefech-alpr/2653668)

**Comment by marshular** [comment]
alright thanks

**Comment by Dev-CasperTheGhost** [comment]
You can download the [first release here](https://github.com/SnailyCAD/fivem-integrations/releases/tag/0.0.1). 
Please see [documentation here](https://cad-docs.caspertheghost.me/docs/fivem-integrations/scripts)
