### ISSUE TITLE
ALPR bug

### ISSUE THREAD

**Issue by ViolentMinds** [SnailyCAD/fivem-integrations#33]
[     script:sna-alpr] SCRIPT ERROR in timer: Error: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.
[     script:sna-alpr] > <unknown> (@sna-alpr/server/server.js:8164)
[     script:sna-alpr]

**Comment by Dev-CasperTheGhost** [comment]
Fixed in [`0.1.0`](https://github.com/SnailyCAD/fivem-integrations/releases/tag/0.1.0)
