### ISSUE TITLE
Reminder: See if we can have it work with spaces in the LP

### ISSUE THREAD

**Issue by Legacy-TacticalGamingInteractive** [SnailyCAD/fivem-integrations#50]
Just a reminder about checking out if we can make it work with spaces.

**Comment by Dev-CasperTheGhost** [comment]
This has been fixed in the latest script release, and on `main` of SnailyCADv4. Make sure to update both before verifying if it was fixed. I was unable to reproduce this issue. Feel free to re-open if it still occurs :)
