### ISSUE TITLE
In-Game: ability to assign self to call via ingame command

### ISSUE THREAD

**Issue by casperiv0** [SnailyCAD/fivem-integrations#53]
1. `/assign` command
1.5 **The user must be authenticated from here -> authentication: Auth via browser linking?**
2. Opens a menu with all the active 911-calls
3. Can click on any of the list items to assign them to the 911 call

**Comment by Dev-CasperTheGhost** [comment]
Idea:

1. Fetch the current user via game identifier
2. In the command, player (in-game) must mention "active officer" or "active ems-fd deputy"
	2.1. player can directly mention the call id here too
4. Opens a menu with all the active 911 calls
5. Player (in-game NUI?) can select any active 911 call to assign themselves too
