### ISSUE TITLE
Duty Status

### ISSUE THREAD

**Issue by marshular** [SnailyCAD/fivem-integrations#73]
Command that sets duty status in the cad

Example:
/status <10-8/10-80/etc.>

Also exports to set and get current status.

(I don't know my 10 codes)

**Comment by Dev-CasperTheGhost** [comment]
Wil see what’s possible later

**Comment by JustCreizy** [comment]
What’s bugging me is that depending on the server and the state for example it’s portraying, some may have differences in the 10 codes. 

For nearly all 10-8 and 10-7 are the same, but the rest vary. 

Example for 10-80
General purpose: Chase in progress 
Norfolk, Virginia: Critical Call (Code Red)
Walnut Creek, California:  Explosion

So if this is gonna be made, it’s probably gonna be:
10-8 On duty 
10-7 off duty 

_That’s my opinion at least_

**Comment by Dev-CasperTheGhost** [comment]
I could possibly fetch all the 10 codes (STATUS_CODE)? This will then allow them to select whichever one they want, I have some ideas and trying to write them down currently

**Comment by Dev-CasperTheGhost** [comment]
Idea:

1. Fetch the current user via game identifier
2. Command opens a menu
3. Able to select any 10-code (STATUS|SITUATION code)
