### ISSUE TITLE
Implement FxDK

### ISSUE THREAD

**Issue by DmACKGL** [SnailyCAD/fivem-integrations#80]
Problem: The integrations are now built and developed outside the server context (no goodies like hot-reload), which seriously impact DX.

Solutions:

- Implement [FxDK](https://docs.fivem.net/docs/fxdk/) for hot-reload (yes, it has hot-reload for TS!) and very beginner-friendly DX
or
- Implement a workflow/script to set the output to FxServer (no hot-reload)

**Comment by Dev-CasperTheGhost** [comment]
1. You can now use `FXSERVER_RESOURCES_PATH="...."` in a `.env` file. This will output the build do the resources folder directly to your FXServer. 
2. A watch/dev command has been added: `pnpm run dev`
