### ISSUE TITLE
call911/tow/taxi exports

### ISSUE THREAD

**Issue by marshular** [SnailyCAD/fivem-integrations#93]
Add exports to the ``sna-call911`` script.

exports:
``exports["sna-call911"]:StartCall(caller_id, call_reason)`` or whatever you see fit
``exports["sna-calltwo"]:StartCall(caller_id, call_reason)`` or whatever you see fit
``exports["sna-calltaxi"]:StartCall(caller_id, call_reason)`` or whatever you see fit

**Comment by casperiv0** [comment]
Actually, looking at the current implementation, this won't be that simple. Therefore I'm also not going to implement this. You can trigger a server event `sn:911CallUpdate` and register a client even for success/failure using `sn:911CallResponse`.

Code: [server](https://github.com/SnailyCAD/fivem-integrations/blob/main/integrations/call911/server/server.ts#L22-L51) and [client](https://github.com/SnailyCAD/fivem-integrations/blob/main/integrations/call911/client/client.ts#L28-L44)
